<?php

/**
 * Implements hook_schema().
 */
function pettys_cart_schema() {
  $schema['pettys_cart'] = [
    'description' => 'Stocke les articles du panier.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Identifiant unique.',
      ],
      'uid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'ID de l’utilisateur (0 pour anonyme).',
      ],
      'product_key' => [
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'description' => 'Clé unique du produit.',
      ],
      'variation_key' => [
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'description' => 'Clé de la variation.',
      ],
      'quantity' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 1,
        'description' => 'Quantité.',
      ],
      'created' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Timestamp de création.',
      ],
    ],
    'primary key' => ['id'],
    'indexes' => [
      'uid' => ['uid'],
      'product_key' => ['product_key'],
    ],
  ];
  return $schema;
}
